@server = https://expert-guide-pp7r47vwjg7h9wp7-8080.app.github.dev
###
GET {{server}}/api/instrumentos
###
POST {{server}}/api/instrumentos
Content-Type: application/json

{"nombre": "Quena", "categoria": "Viento", "descripcion": "Como una flauta"}
###
GET {{server}}/api/musicos/1
###
POST {{server}}/api/musicos
Content-Type: application/json

{"nombre": "Joaquín"}

###
GET {{server}}/api/bandas

###
GET {{server}}/api/integrantes
